# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_creator',
            field=models.CharField(default='', max_length=30),
        ),
    ]
