# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
