# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170409_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Enter City', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='xxx-xxx-xxxx', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='Enter State Abbreviation', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default='Enter Street Address', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='Enter 5-Digit Zipcode', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='First Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=30),
        ),
    ]
