# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170409_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='media/static/pic_folder/'),
        ),
    ]
