# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170409_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/pic_folder/'),
        ),
    ]
